### ISSUE TITLE
How can i delete the cookie after setting it in headers. To reduce request size.

### ISSUE THREAD

**Issue by vorishirne** [pravin-raha/kong-plugin-cookies-to-headers#6]

**Comment by pravin-raha** [comment]
you can do something like this ```ngx.header["Set-Cookie"] = {}```

**Comment by vorishirne** [comment]
It will remove from the client, but need to remove so that upstream is not able to access cookies, but kong is.

**Comment by pravin-raha** [comment]
``` ngx.req.clear_header("Set-Cookie")``` haven't tried this, but this will do the trick
you can also refer [https://github.com/openresty/lua-nginx-module#ngxreqset_header](https://github.com/openresty/lua-nginx-module#ngxreqset_header) this for more details

**Comment by vorishirne** [comment]
Thanks pravin, seems there is no other way. Btw will try set-cookie.
